### ISSUE TITLE
Add tracking_id data attributes to tracking elements 

### ISSUE THREAD

**Issue by lilygdu** [lilygdu/TH-starter#149]
Elements to be tracked (tracking_id):  
1. add to order buttons
2. remove from cart button
3. checkout cart button
4. increment/decrement quantity of items
5. open/close of modals (signout, view receipt details, etc.)
6. any links
7. reorder buttons

Each element should receive the following data attributes:
- [ ] **data-tracking-action**: ex (add-item-to-cart) - NOT NULL
- [ ] **data-tracking-element**: ex (button) - NOT NULL
- [ ] **data-tracking-type**: ex (item) - can be NULL
- [ ] **data-tracking-name**: ex (apple fritter) - can be NULL
- [ ] **data-tracking-id**: ex (apple fritter sanity id) - can be NULL
